// 自社企業データ
export const ourCompanies = [
  { id: "MC001", name: "三菱商事", color_hex: "#EF4444", is_parent: true },
  { id: "MC002", name: "メタルワン", color_hex: "#F97316", is_parent: false },
  { id: "MC003", name: "三菱電機", color_hex: "#10B981", is_parent: false },
  { id: "MC004", name: "三菱重工", color_hex: "#3B82F6", is_parent: false },
  { id: "MC005", name: "三菱ケミカル", color_hex: "#8B5CF6", is_parent: false },
  { id: "MC006", name: "三菱UFJフィナンシャル・グループ", color_hex: "#0EA5E9", is_parent: false },
]

// パートナーグループデータ
export const partnerGroups = [
  {
    id: "HTG001",
    name: "日立グループ",
    industry: "製造業・電子機器",
    companies: ["HT001", "HT002", "HT003", "HT004", "HT005", "HT006"],
  },
  {
    id: "TSG001",
    name: "東芝グループ",
    industry: "製造業・電子機器",
    companies: ["TS001", "TS002", "TS003"],
  },
  {
    id: "PNS001",
    name: "パナソニックグループ",
    industry: "製造業・電子機器",
    companies: ["PN001", "PN002", "PN003"],
  },
  // 富士通グループを追加
  {
    id: "FJG001",
    name: "富士通グループ",
    industry: "IT・システムインテグレーション",
    companies: ["FJ001", "FJ002", "FJ003", "FJ004", "FJ005", "FJ006"],
  },
]

// パートナー企業データ
export const partnerCompanies = [
  { id: "HT001", name: "日立製作所", color_hex: "#1E40AF", group_id: "HTG001", is_parent: true },
  { id: "HT002", name: "日立建機", color_hex: "#3B82F6", group_id: "HTG001", is_parent: false },
  { id: "HT003", name: "日立金属", color_hex: "#8B5CF6", group_id: "HTG001", is_parent: false },
  { id: "HT004", name: "日立化成", color_hex: "#EC4899", group_id: "HTG001", is_parent: false },
  { id: "HT005", name: "日立ハイテク", color_hex: "#06B6D4", group_id: "HTG001", is_parent: false },
  { id: "HT006", name: "日立物流", color_hex: "#14B8A6", group_id: "HTG001", is_parent: false },
  { id: "TS001", name: "東芝", color_hex: "#DC2626", group_id: "TSG001", is_parent: true },
  { id: "TS002", name: "東芝テック", color_hex: "#F59E0B", group_id: "TSG001", is_parent: false },
  { id: "TS003", name: "東芝エネルギーシステムズ", color_hex: "#84CC16", group_id: "TSG001", is_parent: false },
  { id: "PN001", name: "パナソニック", color_hex: "#0284C7", group_id: "PNS001", is_parent: true },
  { id: "PN002", name: "パナソニック コネクト", color_hex: "#7C3AED", group_id: "PNS001", is_parent: false },
  { id: "PN003", name: "パナソニック オートモーティブ", color_hex: "#DB2777", group_id: "PNS001", is_parent: false },
  // 富士通グループ企業を追加
  { id: "FJ001", name: "富士通株式会社", color_hex: "#FF0000", group_id: "FJG001", is_parent: true },
  { id: "FJ002", name: "富士通Japan", color_hex: "#FF5733", group_id: "FJG001", is_parent: false },
  {
    id: "FJ003",
    name: "富士通ネットワークソリューションズ",
    color_hex: "#C70039",
    group_id: "FJG001",
    is_parent: false,
  },
  {
    id: "FJ004",
    name: "富士通クライアントコンピューティング",
    color_hex: "#900C3F",
    group_id: "FJG001",
    is_parent: false,
  },
  { id: "FJ005", name: "富士通フロンテック", color_hex: "#581845", group_id: "FJG001", is_parent: false },
  { id: "FJ006", name: "富士通研究所", color_hex: "#7D3C98", group_id: "FJG001", is_parent: false },
]

// オーナーシップデータ
export const owners = [
  // 既存の日立グループのオーナー
  {
    id: "OW001",
    owner_level: "lead",
    group_id: "HTG001",
    our_company_id: "MC001",
    partner_company_id: null,
    user: "佐藤 一郎",
    title: "取締役副社長",
    phone: "03-1234-5678",
    email: "ichiro.sato@example.com",
  },
  {
    id: "OW002",
    owner_level: "group",
    group_id: "HTG001",
    our_company_id: "MC002",
    partner_company_id: null,
    user: "田中 次郎",
    title: "営業本部長",
    phone: "03-2345-6789",
    email: "jiro.tanaka@example.com",
  },
  {
    id: "OW003",
    owner_level: "company",
    group_id: "HTG001",
    our_company_id: "MC002",
    partner_company_id: "HT001",
    user: "渡辺 六郎",
    title: "アカウントマネージャー",
    phone: "03-3456-7890",
    email: "rokuro.watanabe@example.com",
  },
  {
    id: "OW004",
    owner_level: "group",
    group_id: "HTG001",
    our_company_id: "MC001",
    partner_company_id: null,
    user: "山田 三郎",
    title: "事業開発部長",
    phone: "03-4567-8901",
    email: "saburo.yamada@example.com",
  },
  {
    id: "OW005",
    owner_level: "company",
    group_id: "HTG001",
    our_company_id: "MC001",
    partner_company_id: "HT002",
    user: "鈴木 四郎",
    title: "シニアマネージャー",
    phone: "03-5678-9012",
    email: "shiro.suzuki@example.com",
  },
  {
    id: "OW006",
    owner_level: "company",
    group_id: "HTG001",
    our_company_id: "MC001",
    partner_company_id: "HT003",
    user: "高橋 五郎",
    title: "マネージャー",
    phone: "03-6789-0123",
    email: "goro.takahashi@example.com",
  },
  {
    id: "OW007",
    owner_level: "lead",
    group_id: "TSG001",
    our_company_id: "MC003",
    partner_company_id: null,
    user: "伊藤 七郎",
    title: "常務取締役",
    phone: "03-7890-1234",
    email: "nanaro.ito@example.com",
  },
  {
    id: "OW008",
    owner_level: "lead",
    group_id: "PNS001",
    our_company_id: "MC005",
    partner_company_id: null,
    user: "中村 八郎",
    title: "執行役員",
    phone: "03-8901-2345",
    email: "hachiro.nakamura@example.com",
  },
  // 富士通グループのオーナーを追加
  {
    id: "OW101",
    owner_level: "lead",
    group_id: "FJG001",
    our_company_id: "MC001",
    partner_company_id: null,
    user: "高橋 誠",
    title: "常務執行役員",
    phone: "03-5555-1111",
    email: "makoto.takahashi@example.com",
  },
  {
    id: "OW102",
    owner_level: "group",
    group_id: "FJG001",
    our_company_id: "MC003",
    partner_company_id: null,
    user: "木村 大輔",
    title: "デジタル戦略部長",
    phone: "03-5555-2222",
    email: "daisuke.kimura@example.com",
  },
  {
    id: "OW103",
    owner_level: "group",
    group_id: "FJG001",
    our_company_id: "MC006",
    partner_company_id: null,
    user: "中島 真理",
    title: "IT推進部長",
    phone: "03-5555-3333",
    email: "mari.nakajima@example.com",
  },
  {
    id: "OW104",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC001",
    partner_company_id: "FJ001",
    user: "斎藤 健太",
    title: "デジタルトランスフォーメーション推進室長",
    phone: "03-5555-4444",
    email: "kenta.saito@example.com",
  },
  {
    id: "OW105",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC003",
    partner_company_id: "FJ002",
    user: "山田 直子",
    title: "営業統括部マネージャー",
    phone: "03-5555-5555",
    email: "naoko.yamada@example.com",
  },
  {
    id: "OW106",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC006",
    partner_company_id: "FJ003",
    user: "佐々木 隆",
    title: "ネットワーク部門長",
    phone: "03-5555-6666",
    email: "takashi.sasaki@example.com",
  },
  {
    id: "OW107",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC004",
    partner_company_id: "FJ004",
    user: "田村 美香",
    title: "リテールテクノロジー責任者",
    phone: "03-5555-7777",
    email: "mika.tamura@example.com",
  },
  {
    id: "OW108",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC002",
    partner_company_id: "FJ005",
    user: "井上 拓也",
    title: "調達部長",
    phone: "03-5555-8888",
    email: "takuya.inoue@example.com",
  },
  {
    id: "OW109",
    owner_level: "company",
    group_id: "FJG001",
    our_company_id: "MC005",
    partner_company_id: "FJ006",
    user: "西田 祐子",
    title: "研究開発企画マネージャー",
    phone: "03-5555-9999",
    email: "yuko.nishida@example.com",
  },
]

// 商談データ
export const opportunities = [
  // 既存の日立グループの商談
  {
    id: "OPP001",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    name: "グローバルサプライチェーン構築",
    stage_pct: 75,
    amount_oku: 12.5,
    close_date: "2025-06-30",
    description:
      "グローバルサプライチェーンの構築プロジェクト。日立製作所のグローバル拠点における物流最適化と在庫管理の効率化を目的としている。AIを活用した需要予測と自動発注システムの導入も含む。",
    created_at: "2025-03-15",
    updated_at: "2025-05-10",
    assigned_to: "佐藤 一郎",
    next_action: "最終提案書の提出",
    next_action_date: "2025-05-25",
  },
  {
    id: "OPP002",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    name: "AI駆動型予測保守システム",
    stage_pct: 50,
    amount_oku: 8.3,
    close_date: "2025-08-15",
    description:
      "AIを活用した予測保守システムの開発と導入。日立製作所の製造設備の稼働データを分析し、故障予測と最適なメンテナンスタイミングを提案するシステム。",
    created_at: "2025-02-20",
    updated_at: "2025-04-30",
    assigned_to: "山田 三郎",
    next_action: "技術検証結果のレビュー",
    next_action_date: "2025-05-20",
  },
  {
    id: "OPP003",
    partner_company_id: "HT002",
    our_company_id: "MC002",
    name: "建設機械リース拡大",
    stage_pct: 25,
    amount_oku: 15.7,
    close_date: "2025-07-22",
    description:
      "日立建機の建設機械のリース事業拡大に関するプロジェクト。アジア新興国市場を対象としたリースプログラムの開発と展開。",
    created_at: "2025-03-05",
    updated_at: "2025-04-15",
    assigned_to: "田中 次郎",
    next_action: "市場調査レポートの共有",
    next_action_date: "2025-05-15",
  },
  {
    id: "OPP004",
    partner_company_id: "HT003",
    our_company_id: "MC002",
    name: "特殊合金共同開発",
    stage_pct: 10,
    amount_oku: 6.2,
    close_date: "2025-09-10",
    description: "次世代電気自動車向けの特殊合金の共同開発プロジェクト。軽量かつ高強度の新素材開発を目指す。",
    created_at: "2025-04-01",
    updated_at: "2025-04-20",
    assigned_to: "渡辺 六郎",
    next_action: "初期研究計画の策定",
    next_action_date: "2025-05-30",
  },
  {
    id: "OPP005",
    partner_company_id: "HT004",
    our_company_id: "MC001",
    name: "環境配慮型素材研究",
    stage_pct: 30,
    amount_oku: 9.8,
    close_date: "2025-10-05",
    description: "環境負荷の少ない新素材の研究開発プロジェクト。生分解性プラスチックの代替となる素材の開発と実用化。",
    created_at: "2025-01-15",
    updated_at: "2025-04-25",
    assigned_to: "高橋 五郎",
    next_action: "試作品の評価テスト",
    next_action_date: "2025-06-10",
  },
  {
    id: "OPP006",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    name: "スマートファクトリー導入",
    stage_pct: 15,
    amount_oku: 20.3,
    close_date: "2025-11-20",
    description:
      "日立製作所の主要工場におけるスマートファクトリー化プロジェクト。IoTセンサーとAIを活用した生産ラインの最適化と自動化。",
    created_at: "2025-04-10",
    updated_at: "2025-05-05",
    assigned_to: "佐藤 一郎",
    next_action: "コンセプト提案プレゼンテーション",
    next_action_date: "2025-06-05",
  },
  {
    id: "OPP007",
    partner_company_id: "HT006",
    our_company_id: "MC002",
    name: "物流最適化プロジェクト",
    stage_pct: 60,
    amount_oku: 7.5,
    close_date: "2025-08-30",
    description: "日立物流の配送ネットワーク最適化プロジェクト。AIを活用した配送ルート最適化と車両稼働率向上を目指す。",
    created_at: "2025-02-10",
    updated_at: "2025-05-01",
    assigned_to: "田中 次郎",
    next_action: "システム要件の最終確認",
    next_action_date: "2025-05-20",
  },
  // 富士通グループの商談を追加
  {
    id: "OPP101",
    partner_company_id: "FJ001",
    our_company_id: "MC001",
    name: "デジタルトランスフォーメーション共創プロジェクト",
    stage_pct: 60,
    amount_oku: 25.8,
    close_date: "2025-09-30",
    description:
      "富士通と共同でのデジタルトランスフォーメーション推進プロジェクト。業務プロセスの抜本的な見直しとAI・クラウド技術を活用した新しい業務モデルの構築を目指す。",
    created_at: "2025-02-20",
    updated_at: "2025-05-05",
    assigned_to: "高橋 誠",
    next_action: "経営層向けプレゼンテーション",
    next_action_date: "2025-05-30",
  },
  {
    id: "OPP102",
    partner_company_id: "FJ002",
    our_company_id: "MC003",
    name: "SCM高度化クラウドプラットフォーム",
    stage_pct: 85,
    amount_oku: 14.2,
    close_date: "2025-07-15",
    description:
      "サプライチェーンマネジメントの高度化を目的としたクラウドプラットフォームの構築。リアルタイムでの在庫管理、需要予測、配送最適化を実現する。",
    created_at: "2025-01-10",
    updated_at: "2025-05-01",
    assigned_to: "木村 大輔",
    next_action: "最終契約書の締結",
    next_action_date: "2025-05-20",
  },
  {
    id: "OPP103",
    partner_company_id: "FJ003",
    our_company_id: "MC006",
    name: "グローバルネットワーク基盤刷新",
    stage_pct: 40,
    amount_oku: 18.7,
    close_date: "2025-11-20",
    description:
      "グローバル拠点を結ぶネットワーク基盤の刷新プロジェクト。セキュリティ強化とパフォーマンス向上を目的としている。",
    created_at: "2025-03-05",
    updated_at: "2025-04-28",
    assigned_to: "佐々木 隆",
    next_action: "技術検証結果のレビュー",
    next_action_date: "2025-06-10",
  },
  {
    id: "OPP104",
    partner_company_id: "FJ004",
    our_company_id: "MC004",
    name: "次世代コンビニPOSシステム開発",
    stage_pct: 30,
    amount_oku: 22.5,
    close_date: "2026-01-30",
    description:
      "コンビニエンスストア向けの次世代POSシステム開発。AIを活用した需要予測、顧客行動分析、在庫最適化機能を備える。",
    created_at: "2025-04-01",
    updated_at: "2025-05-02",
    assigned_to: "田村 美香",
    next_action: "要件定義書の承認",
    next_action_date: "2025-06-15",
  },
  {
    id: "OPP105",
    partner_company_id: "FJ005",
    our_company_id: "MC002",
    name: "RFIDサプライチェーン管理システム",
    stage_pct: 70,
    amount_oku: 8.3,
    close_date: "2025-08-15",
    description: "RFIDを活用したサプライチェーン管理システムの構築。物流の可視化と追跡性の向上を実現する。",
    created_at: "2025-02-15",
    updated_at: "2025-04-25",
    assigned_to: "井上 拓也",
    next_action: "パイロット導入の評価",
    next_action_date: "2025-05-25",
  },
  {
    id: "OPP106",
    partner_company_id: "FJ006",
    our_company_id: "MC005",
    name: "食品トレーサビリティAI共同研究",
    stage_pct: 25,
    amount_oku: 5.4,
    close_date: "2025-12-10",
    description:
      "食品のトレーサビリティ向上のためのAI技術の共同研究。ブロックチェーンとAIを組み合わせた新しいトレーサビリティシステムの開発を目指す。",
    created_at: "2025-04-10",
    updated_at: "2025-05-05",
    assigned_to: "西田 祐子",
    next_action: "研究計画の策定",
    next_action_date: "2025-06-01",
  },
  {
    id: "OPP107",
    partner_company_id: "FJ001",
    our_company_id: "MC006",
    name: "グローバル財務システム統合",
    stage_pct: 55,
    amount_oku: 32.1,
    close_date: "2025-10-25",
    description:
      "グローバルに展開する財務システムの統合プロジェクト。リアルタイムでの財務状況把握と意思決定支援を実現する。",
    created_at: "2025-03-01",
    updated_at: "2025-04-20",
    assigned_to: "中島 真理",
    next_action: "システム要件の最終確認",
    next_action_date: "2025-05-30",
  },
  {
    id: "OPP108",
    partner_company_id: "FJ003",
    our_company_id: "MC001",
    name: "海外拠点セキュアネットワーク構築",
    stage_pct: 45,
    amount_oku: 11.7,
    close_date: "2025-09-15",
    description:
      "海外拠点向けのセキュアなネットワーク構築プロジェクト。最新のセキュリティ技術を導入し、リモートワーク環境の強化も図る。",
    created_at: "2025-03-20",
    updated_at: "2025-04-30",
    assigned_to: "斎藤 健太",
    next_action: "セキュリティ要件の確定",
    next_action_date: "2025-06-05",
  },
  {
    id: "OPP109",
    partner_company_id: "FJ002",
    our_company_id: "MC005",
    name: "食肉加工工場スマートファクトリー化",
    stage_pct: 20,
    amount_oku: 17.3,
    close_date: "2026-02-20",
    description:
      "食肉加工工場のスマートファクトリー化プロジェクト。IoTセンサーとAIを活用した生産ラインの最適化と品質管理の強化を実現する。",
    created_at: "2025-04-15",
    updated_at: "2025-05-10",
    assigned_to: "西田 祐子",
    next_action: "現場調査と初期分析",
    next_action_date: "2025-06-20",
  },
  {
    id: "OPP110",
    partner_company_id: "FJ004",
    our_company_id: "MC001",
    name: "本社ワークスタイル変革プロジェクト",
    stage_pct: 90,
    amount_oku: 9.5,
    close_date: "2025-06-30",
    description:
      "本社オフィスのワークスタイル変革プロジェクト。最新のデジタルツールとオフィス環境の整備により、生産性と創造性の向上を目指す。",
    created_at: "2025-01-20",
    updated_at: "2025-05-15",
    assigned_to: "高橋 誠",
    next_action: "最終導入計画の承認",
    next_action_date: "2025-05-25",
  },
]

// アカウントエグゼクティブデータ
export const accountExecutives = [
  {
    id: "AE001",
    partner_company_id: "HT001",
    name: "日立 太郎",
    title: "執行役員",
    phone: "03-1111-1111",
    email: "taro.hitachi@example.com",
    color_hex: "#1E40AF",
    frequency: "High",
    contacts: 12,
  },
  {
    id: "AE002",
    partner_company_id: "HT001",
    name: "日立 花子",
    title: "営業部長",
    phone: "03-2222-2222",
    email: "hanako.hitachi@example.com",
    color_hex: "#1E40AF",
    frequency: "Medium",
    contacts: 8,
  },
  {
    id: "AE003",
    partner_company_id: "HT002",
    name: "日立 三郎",
    title: "技術部長",
    phone: "03-3333-3333",
    email: "saburo.hitachi@example.com",
    color_hex: "#3B82F6",
    frequency: "Low",
    contacts: 4,
  },
  {
    id: "AE004",
    partner_company_id: "HT003",
    name: "日立 四郎",
    title: "事業開発部長",
    phone: "03-4444-4444",
    email: "shiro.hitachi@example.com",
    color_hex: "#8B5CF6",
    frequency: "Medium",
    contacts: 7,
  },
  {
    id: "AE005",
    partner_company_id: "HT004",
    name: "日立 五郎",
    title: "マーケティング部長",
    phone: "03-5555-5555",
    email: "goro.hitachi@example.com",
    color_hex: "#EC4899",
    frequency: "High",
    contacts: 10,
  },
  {
    id: "AE006",
    partner_company_id: "HT005",
    name: "日立 六郎",
    title: "研究開発部長",
    phone: "03-6666-6666",
    email: "rokuro.hitachi@example.com",
    color_hex: "#06B6D4",
    frequency: "Medium",
    contacts: 6,
  },
  {
    id: "AE007",
    partner_company_id: "HT006",
    name: "日立 七郎",
    title: "物流部長",
    phone: "03-7777-7777",
    email: "nanaro.hitachi@example.com",
    color_hex: "#14B8A6",
    frequency: "High",
    contacts: 9,
  },
  // 富士通グループのアカウントエグゼクティブを追加
  {
    id: "AE101",
    partner_company_id: "FJ001",
    name: "藤田 晃",
    title: "専務取締役",
    phone: "03-7777-1111",
    email: "akira.fujita@example.com",
    color_hex: "#FF0000",
    frequency: "High",
    contacts: 15,
  },
  {
    id: "AE102",
    partner_company_id: "FJ001",
    name: "秋山 智子",
    title: "営業本部長",
    phone: "03-7777-1112",
    email: "tomoko.akiyama@example.com",
    color_hex: "#FF0000",
    frequency: "Medium",
    contacts: 9,
  },
  {
    id: "AE103",
    partner_company_id: "FJ002",
    name: "岡本 修",
    title: "執行役員",
    phone: "03-7777-2111",
    email: "osamu.okamoto@example.com",
    color_hex: "#FF5733",
    frequency: "High",
    contacts: 11,
  },
  {
    id: "AE104",
    partner_company_id: "FJ002",
    name: "橋本 恵",
    title: "パートナービジネス部長",
    phone: "03-7777-2112",
    email: "megumi.hashimoto@example.com",
    color_hex: "#FF5733",
    frequency: "Medium",
    contacts: 7,
  },
  {
    id: "AE105",
    partner_company_id: "FJ003",
    name: "村田 哲也",
    title: "代表取締役社長",
    phone: "03-7777-3111",
    email: "tetsuya.murata@example.com",
    color_hex: "#C70039",
    frequency: "Low",
    contacts: 4,
  },
  {
    id: "AE106",
    partner_company_id: "FJ003",
    name: "新井 雄介",
    title: "ソリューション営業部長",
    phone: "03-7777-3112",
    email: "yusuke.arai@example.com",
    color_hex: "#C70039",
    frequency: "Medium",
    contacts: 8,
  },
  {
    id: "AE107",
    partner_company_id: "FJ004",
    name: "松井 大地",
    title: "営業担当執行役員",
    phone: "03-7777-4111",
    email: "daichi.matsui@example.com",
    color_hex: "#900C3F",
    frequency: "Medium",
    contacts: 6,
  },
  {
    id: "AE108",
    partner_company_id: "FJ005",
    name: "上田 真由美",
    title: "事業開発部長",
    phone: "03-7777-5111",
    email: "mayumi.ueda@example.com",
    color_hex: "#581845",
    frequency: "High",
    contacts: 10,
  },
  {
    id: "AE109",
    partner_company_id: "FJ006",
    name: "吉岡 浩",
    title: "研究主幹",
    phone: "03-7777-6111",
    email: "hiroshi.yoshioka@example.com",
    color_hex: "#7D3C98",
    frequency: "Low",
    contacts: 5,
  },
  {
    id: "AE110",
    partner_company_id: "FJ006",
    name: "河野 裕子",
    title: "オープンイノベーション推進室長",
    phone: "03-7777-6112",
    email: "yuko.kono@example.com",
    color_hex: "#7D3C98",
    frequency: "Medium",
    contacts: 7,
  },
]

// コンタクト履歴データ
export const contactHistory = [
  {
    id: "CH001",
    exec_id: "AE001",
    our_company_id: "MC001",
    our_user: "佐藤 一郎",
    date: "2025-04-15",
    purpose: "年間契約更新の打ち合わせ",
    location: "オンライン",
    summary: "年間契約の更新について協議。前年比10%増の予算で合意。新規プロジェクトの可能性についても議論した。",
  },
  {
    id: "CH002",
    exec_id: "AE001",
    our_company_id: "MC002",
    our_user: "田中 次郎",
    date: "2025-03-22",
    purpose: "新規プロジェクト提案",
    location: "日立本社",
    summary: "グローバルサプライチェーン構築に関する新規プロジェクトを提案。日立側から技術的な質問が多く出された。",
  },
  {
    id: "CH003",
    exec_id: "AE001",
    our_company_id: "MC001",
    our_user: "佐藤 一郎",
    date: "2025-02-10",
    purpose: "四半期レビュー会議",
    location: "三菱商事本社",
    summary: "第3四半期の進捗状況をレビュー。全体的に計画通りだが、一部プロジェクトで遅延が発生している。",
  },
  {
    id: "CH004",
    exec_id: "AE001",
    our_company_id: "MC001",
    our_user: "山田 三郎",
    date: "2025-01-05",
    purpose: "新年挨拶・年間計画共有",
    location: "帝国ホテル",
    summary: "新年の挨拶と2025年度の年間計画を共有。両社の戦略的方向性が一致していることを確認した。",
  },
  {
    id: "CH005",
    exec_id: "AE001",
    our_company_id: "MC001",
    our_user: "佐藤 一郎",
    date: "2024-12-15",
    purpose: "年末総括ミーティング",
    location: "オンライン",
    summary: "2024年の活動を総括し、成功事例と課題を共有。来年度に向けた改善点について議論した。",
  },
  {
    id: "CH006",
    exec_id: "AE002",
    our_company_id: "MC001",
    our_user: "山田 三郎",
    date: "2025-04-05",
    purpose: "AI予測保守システム打ち合わせ",
    location: "三菱商事本社",
    summary: "AI駆動型予測保守システムの詳細仕様について協議。技術的な実現可能性と導入スケジュールを確認した。",
  },
  {
    id: "CH007",
    exec_id: "AE003",
    our_company_id: "MC002",
    our_user: "田中 次郎",
    date: "2025-03-15",
    purpose: "建設機械リース事業協議",
    location: "メタルワン本社",
    summary: "アジア市場における建設機械リース事業の展開について協議。市場調査の結果を共有し、事業計画の骨子を固めた。",
  },
  // 富士通グループのコンタクト履歴を追加
  {
    id: "CH101",
    exec_id: "AE101",
    our_company_id: "MC001",
    our_user: "高橋 誠",
    date: "2025-05-06",
    purpose: "デジタル戦略会議",
    location: "富士通本社",
    summary:
      "デジタル戦略に関する会議。両社のDX推進における協業可能性について議論。特にAIとクラウド活用について重点的に協議した。",
  },
  {
    id: "CH102",
    exec_id: "AE102",
    our_company_id: "MC001",
    our_user: "斎藤 健太",
    date: "2025-05-02",
    purpose: "システム連携検討会",
    location: "三菱商事本社",
    summary:
      "システム連携に関する技術的な検討会。API連携の方式とセキュリティ要件について合意。今後の開発スケジュールも確認した。",
  },
  {
    id: "CH103",
    exec_id: "AE103",
    our_company_id: "MC003",
    our_user: "木村 大輔",
    date: "2025-04-28",
    purpose: "クラウド移行プロジェクト会議",
    location: "オンライン",
    summary:
      "クラウド移行プロジェクトの進捗確認。現在のフェーズは計画通り進行中。次フェーズの準備事項について協議した。",
  },
  {
    id: "CH104",
    exec_id: "AE105",
    our_company_id: "MC006",
    our_user: "佐々木 隆",
    date: "2025-04-24",
    purpose: "ネットワークセキュリティ対策会議",
    location: "富士通ネットワークソリューションズ本社",
    summary:
      "ネットワークセキュリティ強化に関する会議。最新のセキュリティ脅威と対策について情報共有。今後の対応方針について合意した。",
  },
  {
    id: "CH105",
    exec_id: "AE107",
    our_company_id: "MC004",
    our_user: "田村 美香",
    date: "2025-04-20",
    purpose: "店舗DX構想検討",
    location: "三菱重工本社",
    summary: "小売店舗のDX推進に関する構想検討。POSシステムの刷新と顧客体験向上のための技術導入について議論した。",
  },
  {
    id: "CH106",
    exec_id: "AE108",
    our_company_id: "MC002",
    our_user: "井上 拓也",
    date: "2025-04-18",
    purpose: "RFID実証実験計画会議",
    location: "メタルワン本社",
    summary:
      "RFIDを活用したサプライチェーン管理の実証実験計画について協議。実験の範囲、期間、評価指標について合意した。",
  },
  {
    id: "CH107",
    exec_id: "AE109",
    our_company_id: "MC005",
    our_user: "西田 祐子",
    date: "2025-04-15",
    purpose: "AIイノベーションワークショップ",
    location: "富士通研究所",
    summary:
      "AIを活用したイノベーションに関するワークショップ。食品安全分野におけるAI活用の可能性について議論し、共同研究の方向性を検討した。",
  },
  {
    id: "CH108",
    exec_id: "AE101",
    our_company_id: "MC001",
    our_user: "高橋 誠",
    date: "2025-04-10",
    purpose: "役員レベル戦略会議",
    location: "帝国ホテル",
    summary:
      "役員レベルでの戦略会議。両社の中長期的な協業ビジョンについて議論し、重点分野の選定と推進体制について合意した。",
  },
  {
    id: "CH109",
    exec_id: "AE104",
    our_company_id: "MC003",
    our_user: "山田 直子",
    date: "2025-04-05",
    purpose: "パートナーシッププログラム検討",
    location: "三菱電機本社",
    summary:
      "パートナーシッププログラムの検討会議。両社のリソースを活用した新しい協業モデルについて議論し、次回までに具体案を準備することになった。",
  },
  {
    id: "CH110",
    exec_id: "AE110",
    our_company_id: "MC005",
    our_user: "西田 祐子",
    date: "2025-04-01",
    purpose: "オープンイノベーション打ち合わせ",
    location: "三菱ケミカル研究所",
    summary:
      "オープンイノベーションに関する打ち合わせ。両社の研究開発リソースを活用した新規事業創出の可能性について議論した。",
  },
]

// 関連会議データ
export const meetings = [
  {
    id: "MTG001",
    opportunity_id: "OPP001",
    date: "2025年4月15日",
    title: "初回提案ミーティング",
    participants: ["佐藤 一郎", "田中 次郎", "日立 太郎"],
    location: "オンライン",
    summary: "グローバルサプライチェーン構築に関する初回提案。日立側から技術的な質問が多く出された。",
  },
  {
    id: "MTG002",
    opportunity_id: "OPP001",
    date: "2025年4月28日",
    title: "技術詳細レビュー",
    participants: ["山田 三郎", "渡辺 六郎", "日立 花子", "日立 三郎"],
    location: "日立本社",
    summary: "技術的な詳細についてのレビュー。セキュリティ面での懸念点が指摘された。",
  },
  {
    id: "MTG003",
    opportunity_id: "OPP001",
    date: "2025年5月10日",
    title: "予算協議",
    participants: ["佐藤 一郎", "鈴木 四郎", "日立 太郎"],
    location: "三菱商事本社",
    summary: "予算の詳細について協議。初期フェーズの範囲を縮小し、段階的に展開する方針で合意。",
  },
  {
    id: "MTG004",
    opportunity_id: "OPP002",
    date: "2025年3月10日",
    title: "コンセプト提案",
    participants: ["山田 三郎", "日立 花子", "日立 六郎"],
    location: "オンライン",
    summary: "AI駆動型予測保守システムのコンセプト提案。日立側から具体的なユースケースの提示を求められた。",
  },
  {
    id: "MTG005",
    opportunity_id: "OPP002",
    date: "2025年4月05日",
    title: "ユースケース検討会",
    participants: ["山田 三郎", "高橋 五郎", "日立 花子", "日立 六郎"],
    location: "日立製作所研究所",
    summary: "具体的なユースケースを5つ提示し、優先順位付けを行った。最初のPoCとして製造ラインの予測保守を選定。",
  },
  {
    id: "MTG006",
    opportunity_id: "OPP003",
    date: "2025年3月20日",
    title: "市場調査報告会",
    participants: ["田中 次郎", "渡辺 六郎", "日立 三郎"],
    location: "メタルワン本社",
    summary:
      "アジア市場における建設機械需要の調査結果を報告。特にインドネシア、ベトナム、フィリピンの成長性が高いことを確認。",
  },
  // 富士通グループの関連会議を追加
  {
    id: "MTG101",
    opportunity_id: "OPP101",
    date: "2025年5月10日",
    title: "DX推進戦略会議",
    participants: ["高橋 誠", "斎藤 健太", "藤田 晃", "秋山 智子"],
    location: "富士通本社",
    summary: "デジタルトランスフォーメーション共創プロジェクトの戦略会議。全体ビジョンと推進体制について合意した。",
  },
  {
    id: "MTG102",
    opportunity_id: "OPP101",
    date: "2025年4月25日",
    title: "技術検討ワークショップ",
    participants: ["斎藤 健太", "秋山 智子", "技術担当者5名"],
    location: "三菱商事本社",
    summary:
      "DXプロジェクトの技術要素に関するワークショップ。AI、クラウド、データ連携の各領域について詳細検討を行った。",
  },
  {
    id: "MTG103",
    opportunity_id: "OPP102",
    date: "2025年5月05日",
    title: "SCMプラットフォーム最終レビュー",
    participants: ["木村 大輔", "山田 直子", "岡本 修", "橋本 恵"],
    location: "三菱電機本社",
    summary:
      "SCM高度化クラウドプラットフォームの最終レビュー。すべての要件が満たされていることを確認し、本番移行計画について合意した。",
  },
  {
    id: "MTG104",
    opportunity_id: "OPP103",
    date: "2025年4月20日",
    title: "ネットワーク要件定義会議",
    participants: ["佐々木 隆", "村田 哲也", "新井 雄介", "ネットワーク担当者4名"],
    location: "富士通ネットワークソリューションズ本社",
    summary:
      "グローバルネットワーク基盤刷新の要件定義会議。セキュリティ要件、パフォーマンス要件、運用要件について詳細に協議した。",
  },
  {
    id: "MTG105",
    opportunity_id: "OPP104",
    date: "2025年5月01日",
    title: "POSシステム構想検討会",
    participants: ["田村 美香", "松井 大地", "小売業界専門家3名"],
    location: "三菱重工本社",
    summary:
      "次世代コンビニPOSシステムの構想検討会。顧客体験向上と業務効率化の両面から要件を整理し、優先順位付けを行った。",
  },
  {
    id: "MTG106",
    opportunity_id: "OPP105",
    date: "2025年4月22日",
    title: "RFID実証実験計画会議",
    participants: ["井上 拓也", "上田 真由美", "物流担当者3名"],
    location: "メタルワン本社",
    summary:
      "RFIDサプライチェーン管理システムの実証実験計画会議。実験の範囲、期間、評価指標について詳細に協議し、実施計画書を作成した。",
  },
  {
    id: "MTG107",
    opportunity_id: "OPP106",
    date: "2025年4月18日",
    title: "食品トレーサビリティ研究キックオフ",
    participants: ["西田 祐子", "吉岡 浩", "河野 裕子"],
    location: "富士通研究所",
    summary:
      "食品トレーサビリティAI共同研究のキックオフミーティング。研究目的、アプローチ、役割分担について合意し、初期の実験計画を策定した。",
  },
  {
    id: "MTG108",
    opportunity_id: "OPP107",
    date: "2025年4月30日",
    title: "財務システム要件確認会議",
    participants: ["中島 真理", "藤田 晃", "財務担当者5名"],
    location: "三菱UFJフィナンシャル・グループ本社",
    summary:
      "グローバル財務システム統合の要件確認会議。各地域の要件を整理し、システム全体のアーキテクチャについて合意した。",
  },
  {
    id: "MTG109",
    opportunity_id: "OPP108",
    date: "2025年4月27日",
    title: "セキュリティ設計レビュー",
    participants: ["斎藤 健太", "村田 哲也", "新井 雄介", "セキュリティ専門家3名"],
    location: "三菱商事本社",
    summary:
      "海外拠点セキュアネットワーク構築のセキュリティ設計レビュー。脅威モデルと対策について詳細に検討し、セキュリティ要件を確定した。",
  },
  {
    id: "MTG110",
    opportunity_id: "OPP109",
    date: "2025年5月08日",
    title: "スマートファクトリー現場調査",
    participants: ["西田 祐子", "岡本 修", "橋本 恵", "工場担当者4名"],
    location: "食肉加工工場",
    summary:
      "食肉加工工場のスマートファクトリー化に向けた現場調査。現状の課題を把握し、IoTセンサーの設置箇所と収集するデータ項目について検討した。",
  },
]

// 関連文書データ
export const documents = [
  {
    id: "DOC001",
    opportunity_id: "OPP001",
    name: "提案書_v1.0.pdf",
    type: "提案書",
    uploadedBy: "佐藤 一郎",
    uploadedAt: "2025年4月10日",
  },
  {
    id: "DOC002",
    opportunity_id: "OPP001",
    name: "技術仕様書.xlsx",
    type: "技術資料",
    uploadedBy: "山田 三郎",
    uploadedAt: "2025年4月25日",
  },
  {
    id: "DOC003",
    opportunity_id: "OPP001",
    name: "予算見積り_改訂版.pdf",
    type: "見積書",
    uploadedBy: "鈴木 四郎",
    uploadedAt: "2025年5月8日",
  },
  {
    id: "DOC004",
    opportunity_id: "OPP002",
    name: "AI予測保守_コンセプト資料.pdf",
    type: "提案書",
    uploadedBy: "山田 三郎",
    uploadedAt: "2025年3月8日",
  },
  {
    id: "DOC005",
    opportunity_id: "OPP002",
    name: "ユースケース分析.pptx",
    type: "分析資料",
    uploadedBy: "高橋 五郎",
    uploadedAt: "2025年4月3日",
  },
  {
    id: "DOC006",
    opportunity_id: "OPP003",
    name: "アジア市場調査レポート.pdf",
    type: "調査資料",
    uploadedBy: "田中 次郎",
    uploadedAt: "2025年3月15日",
  },
  // 富士通グループの関連文書を追加
  {
    id: "DOC101",
    opportunity_id: "OPP101",
    name: "DX推進戦略提案書.pdf",
    type: "提案書",
    uploadedBy: "高橋 誠",
    uploadedAt: "2025年4月15日",
  },
  {
    id: "DOC102",
    opportunity_id: "OPP101",
    name: "技術要件定義書.docx",
    type: "技術資料",
    uploadedBy: "斎藤 健太",
    uploadedAt: "2025年4月28日",
  },
  {
    id: "DOC103",
    opportunity_id: "OPP102",
    name: "SCMプラットフォーム設計書.pdf",
    type: "設計書",
    uploadedBy: "木村 大輔",
    uploadedAt: "2025年4月20日",
  },
  {
    id: "DOC104",
    opportunity_id: "OPP102",
    name: "導入計画書.xlsx",
    type: "計画書",
    uploadedBy: "山田 直子",
    uploadedAt: "2025年5月01日",
  },
  {
    id: "DOC105",
    opportunity_id: "OPP103",
    name: "ネットワーク要件定義書.pdf",
    type: "要件定義書",
    uploadedBy: "佐々木 隆",
    uploadedAt: "2025年4月25日",
  },
  {
    id: "DOC106",
    opportunity_id: "OPP104",
    name: "POSシステム構想書.pptx",
    type: "構想書",
    uploadedBy: "田村 美香",
    uploadedAt: "2025年5月05日",
  },
  {
    id: "DOC107",
    opportunity_id: "OPP105",
    name: "RFID実証実験計画書.pdf",
    type: "計画書",
    uploadedBy: "井上 拓也",
    uploadedAt: "2025年4月23日",
  },
  {
    id: "DOC108",
    opportunity_id: "OPP106",
    name: "AI研究計画書.pdf",
    type: "研究計画書",
    uploadedBy: "西田 祐子",
    uploadedAt: "2025年4月19日",
  },
  {
    id: "DOC109",
    opportunity_id: "OPP107",
    name: "財務システム要件書.xlsx",
    type: "要件書",
    uploadedBy: "中島 真理",
    uploadedAt: "2025年5月02日",
  },
  {
    id: "DOC110",
    opportunity_id: "OPP108",
    name: "セキュリティ設計書.pdf",
    type: "設計書",
    uploadedBy: "斎藤 健太",
    uploadedAt: "2025年4月29日",
  },
]

// 取引データ
export const transactions = [
  {
    id: "TX001",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    fy: "2024",
    sales_oku: 14.2,
    cost_oku: 11.8,
    summary: "システム連携プロジェクト",
  },
  {
    id: "TX002",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    fy: "2023",
    sales_oku: 12.8,
    cost_oku: 10.5,
    summary: "デジタルトランスフォーメーション支援",
  },
  {
    id: "TX003",
    partner_company_id: "HT002",
    our_company_id: "MC002",
    fy: "2024",
    sales_oku: 18.5,
    cost_oku: 15.2,
    summary: "建設機械部品供給",
  },
  {
    id: "TX004",
    partner_company_id: "HT003",
    our_company_id: "MC002",
    fy: "2024",
    sales_oku: 9.3,
    cost_oku: 7.6,
    summary: "特殊合金取引",
  },
  {
    id: "TX005",
    partner_company_id: "HT004",
    our_company_id: "MC001",
    fy: "2024",
    sales_oku: 7.8,
    cost_oku: 6.1,
    summary: "化学製品取引",
  },
  {
    id: "TX006",
    partner_company_id: "HT005",
    our_company_id: "MC001",
    fy: "2024",
    sales_oku: 5.2,
    cost_oku: 4.3,
    summary: "半導体製造装置取引",
  },
  {
    id: "TX007",
    partner_company_id: "HT006",
    our_company_id: "MC002",
    fy: "2024",
    sales_oku: 3.7,
    cost_oku: 2.9,
    summary: "物流サービス契約",
  },
  {
    id: "TX008",
    partner_company_id: "HT001",
    our_company_id: "MC001",
    fy: "2022",
    sales_oku: 11.5,
    cost_oku: 9.8,
    summary: "基幹システム更新プロジェクト",
  },
  {
    id: "TX009",
    partner_company_id: "HT002",
    our_company_id: "MC002",
    fy: "2023",
    sales_oku: 16.7,
    cost_oku: 13.9,
    summary: "建設機械部品供給",
  },
  {
    id: "TX010",
    partner_company_id: "HT002",
    our_company_id: "MC002",
    fy: "2022",
    sales_oku: 15.2,
    cost_oku: 12.8,
    summary: "建設機械部品供給",
  },
  // 富士通グループの取引を追加
  {
    id: "TX101",
    partner_company_id: "FJ001",
    our_company_id: "MC001",
    fy: "2024",
    sales_oku: 32.7,
    cost_oku: 27.8,
    summary: "基幹システム刷新プロジェクト",
  },
  {
    id: "TX102",
    partner_company_id: "FJ002",
    our_company_id: "MC003",
    fy: "2024",
    sales_oku: 18.4,
    cost_oku: 14.9,
    summary: "物流管理システム導入",
  },
  {
    id: "TX103",
    partner_company_id: "FJ004",
    our_company_id: "MC004",
    fy: "2024",
    sales_oku: 25.6,
    cost_oku: 21.2,
    summary: "店舗システム運用保守",
  },
  {
    id: "TX104",
    partner_company_id: "FJ001",
    our_company_id: "MC001",
    fy: "2023",
    sales_oku: 28.9,
    cost_oku: 24.3,
    summary: "グローバルITインフラ整備",
  },
  {
    id: "TX105",
    partner_company_id: "FJ003",
    our_company_id: "MC006",
    fy: "2023",
    sales_oku: 15.7,
    cost_oku: 12.8,
    summary: "SDN導入プロジェクト",
  },
  {
    id: "TX106",
    partner_company_id: "FJ005",
    our_company_id: "MC002",
    fy: "2023",
    sales_oku: 9.8,
    cost_oku: 7.5,
    summary: "金属加工デジタル管理システム",
  },
  {
    id: "TX107",
    partner_company_id: "FJ001",
    our_company_id: "MC001",
    fy: "2022",
    sales_oku: 24.5,
    cost_oku: 20.6,
    summary: "クラウド移行プロジェクト",
  },
  {
    id: "TX108",
    partner_company_id: "FJ006",
    our_company_id: "MC005",
    fy: "2022",
    sales_oku: 4.2,
    cost_oku: 3.5,
    summary: "食品安全AIプロジェクト",
  },
  {
    id: "TX109",
    partner_company_id: "FJ002",
    our_company_id: "MC003",
    fy: "2022",
    sales_oku: 12.6,
    cost_oku: 10.1,
    summary: "物流効率化コンサルティング",
  },
  {
    id: "TX110",
    partner_company_id: "FJ003",
    our_company_id: "MC006",
    fy: "2022",
    sales_oku: 8.9,
    cost_oku: 7.3,
    summary: "セキュリティ強化プロジェクト",
  },
]

// ヘルパー関数
export function getCompanyById(id: string) {
  return [...ourCompanies, ...partnerCompanies].find((company) => company.id === id)
}

export function getOpportunityById(id: string) {
  return opportunities.find((opp) => opp.id === id)
}

export function getMeetingsByOpportunityId(opportunityId: string) {
  return meetings.filter((meeting) => meeting.opportunity_id === opportunityId)
}

export function getDocumentsByOpportunityId(opportunityId: string) {
  return documents.filter((doc) => doc.opportunity_id === opportunityId)
}

export function getContactHistoryByExecId(execId: string) {
  return contactHistory.filter((contact) => contact.exec_id === execId)
}

export function getStageLabel(stagePct: number) {
  if (stagePct < 30) return "初期段階"
  if (stagePct < 60) return "中間段階"
  return "最終段階"
}

export function getStageColor(stagePct: number) {
  if (stagePct < 30) return "bg-indigo-500"
  if (stagePct < 60) return "bg-yellow-500"
  return "bg-green-600"
}
